{
 "title": "Kafka Topic Dashboard (custom)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Avg Delay (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "kafka_producer_avg_delay", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Actual Message Rate ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "kafka_producer_message_rate", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Topic Lambda",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "kafka_producer_lambda", "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Dropped Producer Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kafka_producer_dropped_messages",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Producer Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "kafka_producer_error_rate", "legendFormat": "{{topic}}" }
   ]
  }
 ]
}